AWSTemplateFormatVersion: 2010-09-09
Description: Resources for Python demo app

Resources:
  KDSStream:
    Type: "AWS::Kinesis::Stream"
    Properties:
      Name: python-demo-kds
      RetentionPeriodHours: 24
      ShardCount: 1

  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0be2609ba883822ec
      IamInstanceProfile: AmazonSSMRoleForInstancesQuickSetup
      InstanceType: t2.micro
      SecurityGroupIds:
        - sg-043d8d522d24b646c
      UserData: !Base64
        "Fn::Sub": |
          #!/bin/bash
          yum -y update
          yum install git -y 
          cd /home/ssm-user
          git clone https://github.com/smith8ca/codeguru-python-demo.git
          chmod -R +x *
          chown -R ssm-user:ssm-user *
      Tags:
        - Key: Name
          Value: python-demo
